# Generated by Django 3.2.7 on 2021-11-01 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_img', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('status', models.IntegerField(choices=[(1, 'Admin'), (13, 'Visitor'), (11, 'Teacher'), (12, 'Student')], default=13)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название задания')),
                ('authors', models.ManyToManyField(related_name='Task_authors', to='main.Profile')),
                ('students', models.ManyToManyField(related_name='Task_students', to='main.Profile')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название урока')),
                ('description', models.TextField(default='...', max_length=500, verbose_name='Описание урока')),
                ('students', models.ManyToManyField(related_name='Lesson_students', to='main.Profile')),
                ('tasks', models.ManyToManyField(related_name='Lesson_tasks', to='main.Task')),
                ('teachers', models.ManyToManyField(related_name='Lesson_teachers', to='main.Profile')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название курса')),
                ('description', models.TextField(default='...', max_length=500, verbose_name='описание курса')),
                ('lessons', models.ManyToManyField(related_name='Course_lessons', to='main.Profile')),
                ('students', models.ManyToManyField(related_name='Course_students', to='main.Profile')),
                ('teachers', models.ManyToManyField(related_name='Course_teachers', to='main.Profile')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='имя класса')),
                ('description', models.TextField(default='...', max_length=500, verbose_name='Описание класса')),
                ('students', models.ManyToManyField(related_name='Class_students', to='main.Profile')),
                ('teachers', models.ManyToManyField(related_name='Class_teachers', to='main.Profile')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
    ]
