# Generated by Django 3.2.7 on 2021-11-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_course_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='classes',
            field=models.ManyToManyField(related_name='Course_classes', to='main.Class'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='classes',
            field=models.ManyToManyField(related_name='Lesson_classes', to='main.Class'),
        ),
    ]
